"""种子数据导入（T1.21）：初始管理员 + 系统规则 + 真实媒体源 + GDELT 兜底伪源。

用法：
    cd backend && python ../scripts/seed_sources.py
    （或在仓库根：python scripts/seed_sources.py；数据库 URL 经 .env/环境变量注入）

种子源 URL 均经实测可达（2026-07-24，feedparser 可解析）；
IIS 15 媒体任务参数（Apache-2.0 事实性配置：源 URL、抓取方式）为本清单主要参照。
脚本幂等：按 name 去重，已存在则更新 feed_url/crawl_config 等字段。
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "backend"))

from sqlalchemy import select  # noqa: E402

from app.core.logging import configure_logging, get_logger  # noqa: E402
from app.db.session import get_session_factory, init_engine  # noqa: E402
from app.models.source import Source  # noqa: E402
from app.services.seed_service import (  # noqa: E402
    ensure_admin,
    ensure_gdelt_pseudo_source,
    ensure_system_rules,
)
from app.services.setup_service import (  # noqa: E402
    KEY_MONITOR_SCOPE,
    apply_monitor_scope,
    get_state,
)

logger = get_logger("seed")

# (name, name_zh, country, homepage, feed_url, collect_mode, adapter_type, crawl_config,
#  media_type, language, poll_interval_min, audience_weight, coverage_confidence)
SEED_SOURCES = [
    ("BBC World", "英国广播公司国际新闻", "GB", "https://www.bbc.com/news",
     "https://feeds.bbci.co.uk/news/world/rss.xml", "rss", "rss", None,
     "broadcast", "en", 5, 18.0, "high"),
    ("Voice of America", "美国之音", "US", "https://www.voanews.com",
     "https://www.voanews.com/api/zqboml-vomx-tpeivmy", "rss", "rss", None,
     "broadcast", "en", 5, 15.0, "high"),
    ("TASS", "塔斯社", "RU", "https://tass.com",
     "https://tass.com/rss/v2.xml", "rss", "rss", None,
     "agency", "en", 5, 14.0, "high"),
    ("NHK", "日本放送协会", "JP", "https://www3.nhk.or.jp",
     "https://www3.nhk.or.jp/rss/news/cat0.xml", "rss", "rss", None,
     "broadcast", "ja", 5, 16.0, "high"),
    ("Deutsche Welle", "德国之声", "DE", "https://www.dw.com",
     "https://rss.dw.com/rdf/rss-en-all", "rss", "rss", None,
     "broadcast", "en", 15, 12.0, "high"),
    ("El País", "国家报", "ES", "https://elpais.com",
     "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada", "rss", "rss", None,
     "newspaper", "es", 15, 13.0, "high"),
    ("France 24", "法兰西24", "FR", "https://www.france24.com/en",
     "https://www.france24.com/en/rss", "rss", "rss",
     {"fetcher": {"type": "playwright"}},   # 正文页反爬（403 via requests），Playwright 实测可渲染
     "broadcast", "en", 15, 11.0, "high"),
    ("RFI", "法国国际广播电台", "FR", "https://www.rfi.fr/en",
     "https://www.rfi.fr/en/rss", "rss", "rss",
     {"fetcher": {"type": "playwright"}},
     "broadcast", "en", 15, 9.0, "medium"),
    ("Anadolu Agency", "阿纳多卢通讯社", "TR", "https://www.aa.com.tr",
     "https://www.aa.com.tr/tr/rss/default?cat=guncel", "rss", "rss", None,
     "agency", "tr", 15, 12.0, "medium"),
    ("NTV", "土耳其NTV电视台", "TR", "https://www.ntv.com.tr",
     "https://www.ntv.com.tr/son-dakika.rss", "rss", "rss", None,
     "broadcast", "tr", 15, 10.0, "medium"),
    ("Yonhap News", "韩国联合通讯社", "KR", "https://www.yna.co.kr",
     "https://www.yna.co.kr/rss/news.xml", "rss", "rss", None,
     "agency", "ko", 5, 15.0, "high"),
    ("新华网", "新华网", "CN", "http://www.xinhuanet.com",
     "http://www.xinhuanet.com/politics/news_politics.xml", "rss", "rss", None,
     "agency", "zh-CN", 5, 18.0, "high"),
    ("中新网", "中国新闻网", "CN", "https://www.chinanews.com.cn",
     "https://www.chinanews.com.cn/rss/scroll-news.xml", "rss", "rss", None,
     "agency", "zh-CN", 5, 14.0, "high"),
    ("Al Jazeera", "半岛电视台", "QA", "https://www.aljazeera.com",
     "https://www.aljazeera.com/xml/rss/all.xml", "rss", "rss", None,
     "broadcast", "en", 15, 12.0, "high"),
    ("CBC News", "加拿大广播公司", "CA", "https://www.cbc.ca/news",
     "https://www.cbc.ca/webfeed/rss/rss-topstories", "rss", "rss", None,
     "broadcast", "en", 15, 13.0, "high"),
    ("ABC News (AU)", "澳大利亚广播公司", "AU", "https://www.abc.net.au/news",
     "https://www.abc.net.au/news/feed/51120/rss.xml", "rss", "rss", None,
     "broadcast", "en", 15, 13.0, "high"),
    ("Investing.com", "英为财情", "US", "https://www.investing.com",
     "https://www.investing.com/rss/news.rss", "rss", "rss",
     {"fetcher": {"type": "playwright"}},
     "online", "en", 15, 8.0, "medium"),
    # ---- 30 国扩展（G20 + 全球南方；feed URL 均经代理实测 200 且含 RSS 结构，2026-07-24） ----
    ("Times of India", "印度时报", "IN", "https://timesofindia.indiatimes.com",
     "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "rss", "rss", None,
     "newspaper", "en", 15, 15.0, "high"),
    ("The Hindu", "印度教徒报", "IN", "https://www.thehindu.com",
     "https://www.thehindu.com/news/national/feeder/default.rss", "rss", "rss", None,
     "newspaper", "en", 15, 12.0, "high"),
    ("Antara News", "安塔拉通讯社", "ID", "https://en.antaranews.com",
     "https://en.antaranews.com/rss/news.xml", "rss", "rss", None,
     "agency", "en", 15, 12.0, "medium"),
    ("G1 Globo", "环球网G1", "BR", "https://g1.globo.com",
     "https://g1.globo.com/rss/g1/", "rss", "rss", None,
     "online", "pt", 15, 16.0, "high"),
    ("Folha de S.Paulo", "圣保罗页报", "BR", "https://www.folha.uol.com.br",
     "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml", "rss", "rss", None,
     "newspaper", "pt", 15, 11.0, "medium"),
    ("La Jornada", "墨西哥日报", "MX", "https://www.jornada.com.mx",
     "https://www.jornada.com.mx/rss/edicion.xml?v=1", "rss", "rss", None,
     "newspaper", "es", 15, 11.0, "medium"),
    ("Clarín", "号角报", "AR", "https://www.clarin.com",
     "https://www.clarin.com/rss/lo-ultimo/", "rss", "rss", None,
     "newspaper", "es", 15, 13.0, "medium"),
    ("Al Riyadh", "利雅得报", "SA", "https://www.alriyadh.com",
     "https://www.alriyadh.com/rss/section/main", "rss", "rss",
     {"insecure_ssl": True},   # 证书链异常（CERTIFICATE_VERIFY_FAILED）但内容可用，关闭校验抓取
     "newspaper", "ar", 15, 12.0, "medium"),
    ("eNCA", "南非eNCA电视台", "ZA", "https://www.enca.com",
     "https://www.enca.com/rss.xml", "rss", "rss", None,
     "broadcast", "en", 15, 11.0, "medium"),
    ("ANSA", "安莎通讯社", "IT", "https://www.ansa.it",
     "https://www.ansa.it/sito/notizie/topnews/topnews_rss.xml", "rss", "rss", None,
     "agency", "it", 15, 13.0, "high"),
    ("Corriere della Sera", "晚邮报", "IT", "https://www.corriere.it",
     "https://xml2.corriereobjects.it/rss/homepage.xml", "rss", "rss", None,
     "newspaper", "it", 15, 12.0, "high"),
    ("Daily News Egypt", "埃及每日新闻", "EG", "https://www.dailynewsegypt.com",
     "https://www.dailynewsegypt.com/feed/", "rss", "rss", None,
     "newspaper", "en", 15, 8.0, "medium"),
    ("Vanguard", "先锋报", "NG", "https://www.vanguardngr.com",
     "https://www.vanguardngr.com/feed/", "rss", "rss", None,
     "newspaper", "en", 15, 10.0, "medium"),
    ("The Standard", "标准报", "KE", "https://www.standardmedia.co.ke",
     "https://www.standardmedia.co.ke/rss/headlines.php", "rss", "rss", None,
     "newspaper", "en", 15, 10.0, "medium"),
    ("Bangkok Post", "曼谷邮报", "TH", "https://www.bangkokpost.com",
     "https://www.bangkokpost.com/rss/data/topstories.xml", "rss", "rss", None,
     "newspaper", "en", 15, 9.0, "medium"),
    ("VnExpress", "越南快讯", "VN", "https://vnexpress.net",
     "https://vnexpress.net/rss/tin-moi-nhat.rss", "rss", "rss", None,
     "online", "vi", 15, 13.0, "high"),
    ("The Daily Star", "每日星报", "BD", "https://www.thedailystar.net",
     "https://www.thedailystar.net/frontpage/rss.xml", "rss", "rss", None,
     "newspaper", "en", 15, 9.0, "medium"),
    ("Fana Broadcasting", "法纳广播公司", "ET", "https://www.fanabc.com",
     "https://www.fanabc.com/feed/", "rss", "rss", None,
     "broadcast", "en", 15, 9.0, "medium"),
    ("Tehran Times", "德黑兰时报", "IR", "https://www.tehrantimes.com",
     "https://www.tehrantimes.com/rss", "rss", "rss", None,
     "newspaper", "en", 15, 8.0, "medium"),
    ("Dawn", "黎明报", "PK", "https://www.dawn.com",
     "https://www.dawn.com/feed", "rss", "rss", None,
     "newspaper", "en", 15, 11.0, "medium"),
    ("The National", "国民报", "AE", "https://www.thenationalnews.com",
     "https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml", "rss", "rss", None,
     "newspaper", "en", 15, 8.0, "medium"),
    # ---- 57 国扩展第二波（G20 补足 + 全球南方；feed URL 均经容器内实测 200 且含 RSS 结构，2026-08-01） ----
    ("Mainichi Shimbun", "每日新闻", "JP", "https://mainichi.jp",
     "https://mainichi.jp/rss/etc/english_latest.rss", "rss", "rss", None,
     "newspaper", "en", 15, 10.0, "high"),
    ("The Guardian", "卫报", "GB", "https://www.theguardian.com",
     "https://www.theguardian.com/world/rss", "rss", "rss", None,
     "newspaper", "en", 15, 15.0, "high"),
    ("Sputnik 中文", "卫星通讯社(中文)", "RU", "https://sputniknews.cn",
     "https://sputniknews.cn/export/rss2/archive/index.xml", "rss", "rss", None,
     "agency", "zh-CN", 15, 9.0, "medium"),
    ("Hürriyet", "自由报", "TR", "https://www.hurriyet.com.tr",
     "http://www.hurriyet.com.tr/rss/anasayfa", "rss", "rss", None,
     "newspaper", "tr", 15, 12.0, "high"),
    ("Milliyet", "民族报", "TR", "https://www.milliyet.com.tr",
     "http://www.milliyet.com.tr/rss/rssNew/gundemRss.xml", "rss", "rss", None,
     "newspaper", "tr", 15, 10.0, "medium"),
    ("TRT Haber", "土耳其广播电视公司", "TR", "https://www.trthaber.com",
     "http://www.trthaber.com/sondakika.rss", "rss", "rss", None,
     "broadcast", "tr", 15, 12.0, "high"),
    ("CNN Türk", "CNN土耳其", "TR", "https://www.cnnturk.com",
     "https://www.cnnturk.com/feed/rss/all/news", "rss", "rss", None,
     "broadcast", "tr", 15, 11.0, "medium"),
    ("Yonhap (EN)", "韩联社(英文)", "KR", "https://en.yna.co.kr",
     "https://en.yna.co.kr/RSS/national.xml", "rss", "rss", None,
     "agency", "en", 15, 10.0, "high"),
    ("NRK", "挪威广播公司", "NO", "https://www.nrk.no",
     "https://www.nrk.no/toppsaker.rss", "rss", "rss", None,
     "broadcast", "no", 15, 12.0, "high"),
    ("NOS", "荷兰公共广播", "NL", "https://nos.nl",
     "https://feeds.nos.nl/nosnieuwsalgemeen", "rss", "rss", None,
     "broadcast", "nl", 15, 12.0, "high"),
    ("Dagens Nyheter", "每日新闻报(瑞典)", "SE", "https://www.dn.se",
     "https://www.dn.se/rss/", "rss", "rss", None,
     "newspaper", "sv", 15, 11.0, "high"),
    ("Daily News Tanzania", "坦桑尼亚每日新闻", "TZ", "https://dailynews.co.tz",
     "https://dailynews.co.tz/feed/", "rss", "rss", None,
     "newspaper", "en", 15, 8.0, "medium"),
    ("Daily Monitor", "乌干达每日观察家报", "UG", "https://www.monitor.co.ug",
     "https://www.monitor.co.ug/rss.xml", "rss", "rss", None,
     "newspaper", "en", 15, 8.0, "medium"),
    ("RNZ", "新西兰广播电台", "NZ", "https://www.rnz.co.nz",
     "https://www.rnz.co.nz/rss/world.xml", "rss", "rss", None,
     "broadcast", "en", 15, 11.0, "high"),
    ("Hespress", "赫斯普雷斯报", "MA", "https://en.hespress.com",
     "https://en.hespress.com/feed/", "rss", "rss", None,
     "newspaper", "en", 15, 8.0, "medium"),
    ("Polsat News", "波尔萨特新闻", "PL", "https://www.polsatnews.pl",
     "https://www.polsatnews.pl/rss/", "rss", "rss",
     {"fetcher": {"type": "playwright"}},   # 正文页反爬（403 via requests），Playwright 实测可渲染
     "broadcast", "pl", 15, 9.0, "medium"),
    ("Astana Times", "阿斯塔纳时报", "KZ", "https://astanatimes.com",
     "https://astanatimes.com/feed/", "rss", "rss", None,
     "newspaper", "en", 15, 8.0, "medium"),
    ("NZZ", "新苏黎世报", "CH", "https://www.nzz.ch",
     "https://www.nzz.ch/international.rss", "rss", "rss", None,
     "newspaper", "de", 15, 11.0, "high"),
    # 无 RSS 长尾示例：adapter_type='pipeline'，ListPageDiscoverer 签名聚类免手写 selector
    ("新华网时政列表页", "新华网时政频道(列表页)", "CN", "https://www.news.cn",
     None, "rss", "pipeline",
     {"fetcher": {"type": "requests"}, "discoverer": {"type": "list_page"},
      "extractor": {"type": "trafilatura"}, "entry_points": ["https://www.news.cn/politics/"],
      "scroll_pages": 0, "post_extra_action": None, "proxy": None},
     "agency", "zh-CN", 15, 6.0, "medium"),
    # ---- 108 国扩展第三波（G20 全覆盖 + 全球南方补足 + 欧洲/拉美/中亚/非洲/中东补齐；feed URL 均经代理实测 200 且含 RSS 结构，2026-08-02） ----
    # 拉美 7 国
    ("El Observador (UY)", "观察者报(乌拉圭)", "UY", "https://www.elobservador.com.uy",
     "https://news.google.com/rss/search?q=site:elobservador.com.uy&hl=es&gl=UY&ceid=UY:es",
     "rss", "rss", None, "newspaper", "es", 15, 8.0, "medium"),
    ("El Deber", "责任报(玻利维亚)", "BO", "https://www.eldeber.com.bo",
     "https://news.google.com/rss/search?q=site:eldeber.com.bo&hl=es&gl=BO&ceid=BO:es",
     "rss", "rss", None, "newspaper", "es", 15, 9.0, "medium"),
    ("Expreso", "快报(厄瓜多尔)", "EC", "https://www.expreso.ec",
     "https://www.expreso.ec/rss", "rss", "rss", None,
     "newspaper", "es", 15, 8.0, "medium"),
    ("El Nacional (VE)", "国民报(委内瑞拉)", "VE", "https://www.elnacional.com",
     "https://www.elnacional.com/feed/", "rss", "rss", None,
     "newspaper", "es", 15, 9.0, "medium"),
    ("Diario HOY (PY)", "今日报(巴拉圭)", "PY", "https://www.hoy.com.py",
     "https://www.hoy.com.py/feed/", "rss", "rss", None,
     "newspaper", "es", 15, 8.0, "medium"),
    ("Prensa Latina", "拉丁美洲通讯社", "CU", "https://www.prensa-latina.cu",
     "https://www.prensa-latina.cu/feed/", "rss", "rss", None,
     "agency", "es", 15, 10.0, "high"),
    ("El Nacional (DO)", "国家报(多米尼加)", "DO", "https://elnacional.com.do",
     "https://elnacional.com.do/rss/", "rss", "rss", None,
     "newspaper", "es", 15, 8.0, "medium"),
    # 中亚 8 国
    ("UzDaily", "乌兹别克每日", "UZ", "https://www.uzdaily.uz",
     "https://www.uzdaily.uz/rss", "rss", "rss", None,
     "online", "en", 15, 8.0, "medium"),
    ("Turkmenportal (via GN)", "土库曼门户(谷歌新闻)", "TM", "https://turkmenportal.com",
     "https://news.google.com/rss/search?q=site:turkmenportal.com&hl=ru&gl=TM&ceid=TM:ru",
     "rss", "rss", None, "online", "ru", 15, 7.0, "low"),
    ("AKIpress", "阿克新闻社", "KG", "https://akipress.com",
     "https://akipress.com/rss", "rss", "rss", None,
     "agency", "en", 15, 8.0, "medium"),
    ("Asia-Plus", "亚洲加(塔吉克)", "TJ", "https://asiaplustj.info",
     "https://asiaplustj.info/rss", "rss", "rss", None,
     "online", "ru", 15, 8.0, "medium"),
    ("Trend", "趋势通讯社(阿塞拜疆)", "AZ", "https://en.trend.az",
     "https://en.trend.az/rss", "rss", "rss", None,
     "agency", "en", 15, 9.0, "medium"),
    ("Civil Georgia", "格鲁吉亚公民", "GE", "https://civil.ge",
     "https://civil.ge/feed/", "rss", "rss", None,
     "online", "en", 15, 8.0, "medium"),
    ("Public Radio of Armenia", "亚美尼亚公共广播", "AM", "https://en.armradio.am",
     "https://en.armradio.am/rss", "rss", "rss", None,
     "broadcast", "en", 15, 7.0, "medium"),
    ("BelTA English", "白俄通社(英文)", "BY", "https://eng.belta.by",
     "https://eng.belta.by/rss", "rss", "rss", None,
     "agency", "en", 15, 9.0, "medium"),
    # 中东 6 + 南亚 1 + 东南亚 2 + 大洋洲 1 = 10 国
    ("Iraqi News", "伊拉克新闻", "IQ", "https://www.iraqinews.com",
     "https://www.iraqinews.com/feed/", "rss", "rss", None,
     "online", "en", 15, 8.0, "medium"),
    ("Syrian Arab News Agency", "叙利亚通讯社", "SY", "https://sana.sy/en",
     "https://sana.sy/en/?feed=rss2", "rss", "rss", None,
     "agency", "en", 15, 9.0, "high"),
    ("SABA News Agency", "萨巴通讯社", "YE", "https://www.saba.ye/en",
     "https://www.saba.ye/en/rsscatfeed14.htm", "rss", "rss", None,
     "agency", "en", 15, 8.0, "high"),
    ("Gulf Daily News", "海湾每日新闻", "BH", "https://www.gdnonline.com",
     "https://news.google.com/rss/search?q=site:gdnonline.com&hl=en",
     "rss", "rss", None, "newspaper", "en", 15, 7.0, "medium"),
    ("Times of Oman", "阿曼时报", "OM", "https://www.timesofoman.com",
     "https://www.timesofoman.com/feed/", "rss", "rss", None,
     "newspaper", "en", 15, 8.0, "high"),
    ("Palestine News Network", "巴勒斯坦新闻网", "PS", "https://pnn.ps",
     "https://www.pnn.ps/feed/", "rss", "rss", None,
     "agency", "ar", 15, 7.0, "medium"),
    ("Ariana News", "阿里亚纳新闻", "AF", "https://www.ariananews.af",
     "https://www.ariananews.af/feed/", "rss", "rss", None,
     "broadcast", "en", 15, 8.0, "high"),
    ("Laotian Times", "老挝时报", "LA", "https://laotiantimes.com",
     "https://laotiantimes.com/feed/", "rss", "rss", None,
     "online", "en", 15, 6.0, "medium"),
    ("The Scoop", "文莱The Scoop", "BN", "https://thescoop.co",
     "https://thescoop.co/feed/", "rss", "rss", None,
     "online", "en", 15, 6.0, "medium"),
    ("FBC News", "斐济广播公司", "FJ", "https://www.fbcnews.com.fj",
     "https://www.fbcnews.com.fj/feed/", "rss", "rss", None,
     "broadcast", "en", 15, 7.0, "high"),
    # 欧洲 12 国
    ("Proto Thema", "希腊第一主题报", "GR", "https://www.protothema.gr",
     "https://www.protothema.gr/rss/", "rss", "rss", None,
     "newspaper", "el", 15, 10.0, "high"),
    ("RTP Notícias", "葡萄牙国家广播电台", "PT", "https://www.rtp.pt",
     "https://www.rtp.pt/noticias/rss", "rss", "rss", None,
     "broadcast", "pt", 15, 10.0, "high"),
    ("Iltalehti", "芬兰晚报", "FI", "https://www.iltalehti.fi",
     "https://www.iltalehti.fi/rss.xml", "rss", "rss", None,
     "online", "fi", 15, 9.0, "high"),
    ("DR Nyheder", "丹麦国家广播新闻", "DK", "https://www.dr.dk",
     "https://www.dr.dk/nyheder/service/feeds/allenyheder", "rss", "rss", None,
     "broadcast", "da", 15, 9.0, "high"),
    ("Aktuálně.cz", "捷克在线新闻", "CZ", "https://zpravy.aktualne.cz",
     "https://zpravy.aktualne.cz/rss/", "rss", "rss", None,
     "online", "cs", 15, 9.0, "high"),
    ("Der Standard", "奥地利标准报", "AT", "https://www.derstandard.at",
     "https://www.derstandard.at/rss", "rss", "rss", None,
     "newspaper", "de", 15, 9.0, "high"),
    ("Irish Independent", "爱尔兰独立报", "IE", "https://www.independent.ie",
     "https://www.independent.ie/rss", "rss", "rss", None,
     "newspaper", "en", 15, 10.0, "high"),
    ("Ukrainska Pravda", "乌克兰真理报", "UA", "https://www.pravda.com.ua",
     "https://www.pravda.com.ua/rss/", "rss", "rss", None,
     "online", "uk", 15, 10.0, "high"),
    ("Telex", "匈牙利在线新闻", "HU", "https://telex.hu",
     "https://telex.hu/rss", "rss", "rss", None,
     "online", "hu", 15, 9.0, "high"),
    ("Mediafax", "罗马尼亚媒体传真", "RO", "https://www.mediafax.ro",
     "https://www.mediafax.ro/rss", "rss", "rss", None,
     "agency", "ro", 15, 9.0, "high"),
    ("Vesti.bg", "保加利亚在线新闻", "BG", "https://www.vesti.bg",
     "https://www.vesti.bg/rss", "rss", "rss", None,
     "online", "bg", 15, 8.0, "high"),
    ("SME", "斯洛伐克日报", "SK", "https://www.sme.sk",
     "https://www.sme.sk/rss", "rss", "rss", None,
     "newspaper", "sk", 15, 8.0, "high"),
    # 非洲 14 国
    ("TSA", "TSA阿尔及利亚", "DZ", "https://www.tsa-algerie.com",
     "https://www.tsa-algerie.com/feed/", "rss", "rss", None,
     "online", "fr", 15, 9.0, "high"),
    ("La Presse de Tunisie", "突尼斯新闻报", "TN", "https://www.lapresse.tn",
     "https://www.lapresse.tn/feed/", "rss", "rss", None,
     "newspaper", "fr", 15, 8.0, "high"),
    ("Libya Herald", "利比亚先驱报", "LY", "https://www.libyaherald.com",
     "https://www.libyaherald.com/feed/", "rss", "rss", None,
     "online", "en", 15, 7.0, "medium"),
    ("KT Press", "基加利时报(通讯社)", "RW", "https://ktpress.rw",
     "https://ktpress.rw/feed/", "rss", "rss", None,
     "agency", "en", 15, 7.0, "high"),
    ("SeneNews", "塞内新闻", "SN", "https://www.senenews.com",
     "https://www.senenews.com/feed/", "rss", "rss", None,
     "online", "fr", 15, 8.0, "medium"),
    ("Agence Ivoirienne de Presse", "科特迪瓦通讯社", "CI", "https://www.aip.ci",
     "https://www.aip.ci/feed/", "rss", "rss", None,
     "agency", "fr", 15, 8.0, "high"),
    ("Journal du Cameroun", "喀麦隆日报", "CM", "https://www.journalducameroun.com",
     "https://www.journalducameroun.com/feed/", "rss", "rss", None,
     "online", "fr", 15, 8.0, "medium"),
    ("Portal de Angola", "安哥拉门户网", "AO", "https://www.portaldeangola.com",
     "https://www.portaldeangola.com/feed/", "rss", "rss", None,
     "online", "pt", 15, 7.0, "medium"),
    ("Jornal Notícias", "莫桑比克消息报", "MZ", "https://www.jornalnoticias.co.mz",
     "https://www.jornalnoticias.co.mz/feed/", "rss", "rss", None,
     "newspaper", "pt", 15, 8.0, "high"),
    ("Lusaka Times", "卢萨卡时报", "ZM", "https://www.lusakatimes.com",
     "https://www.lusakatimes.com/feed/", "rss", "rss", None,
     "online", "en", 15, 8.0, "high"),
    ("Bulawayo24", "布拉瓦约24网", "ZW", "https://bulawayo24.com",
     "https://bulawayo24.com/rss", "rss", "rss", None,
     "online", "en", 15, 8.0, "high"),
    ("Weekend Post", "周末邮报", "BW", "https://www.weekendpost.co.bw",
     "https://www.weekendpost.co.bw/feed", "rss", "rss", None,
     "newspaper", "en", 15, 6.0, "medium"),
    ("Gabonreview", "加蓬评论", "GA", "https://www.gabonreview.com",
     "https://www.gabonreview.com/feed/", "rss", "rss", None,
     "online", "fr", 15, 6.0, "medium"),
    ("Radio Okapi", "奥卡皮广播电台", "CD", "https://www.radiookapi.net",
     "https://www.radiookapi.net/rss.xml", "rss", "rss", None,
     "broadcast", "fr", 15, 9.0, "high"),
    # ---- 92→108 国补缺：为原 0 源国家补主流媒体直达源（部分 403/反爬用 Google News site: 聚合兜底，2026-08-02） ----
    ("La Libre", "自由比利时", "BE", "https://www.lalibre.be",
     "https://www.lalibre.be/rss.xml", "rss", "rss", None,
     "newspaper", "fr", 15, 9.0, "medium"),
    ("La Tercera", "第三日报", "CL", "https://www.latercera.com",
     "https://www.latercera.com/rss/", "rss", "rss", None,
     "newspaper", "es", 15, 10.0, "high"),
    ("El Tiempo (via GN)", "时代报(哥伦比亚)", "CO", "https://www.eltiempo.com",
     "https://news.google.com/rss/search?q=site:eltiempo.com&hl=es&gl=CO&ceid=CO:es",
     "rss", "rss", None, "newspaper", "es", 15, 11.0, "medium"),
    ("MyJoyOnline", "加纳喜悦在线", "GH", "https://www.myjoyonline.com",
     "https://www.myjoyonline.com/feed/", "rss", "rss", None,
     "online", "en", 15, 9.0, "medium"),
    ("Haaretz (via GN)", "国土报(以色列)", "IL", "https://www.haaretz.com",
     "https://news.google.com/rss/search?q=site:haaretz.com&hl=en&gl=IL&ceid=IL:en",
     "rss", "rss", None, "newspaper", "en", 15, 10.0, "medium"),
    ("Jordan Times (via GN)", "约旦时报", "JO", "https://www.jordantimes.com",
     "https://news.google.com/rss/search?q=site:jordantimes.com&hl=en&gl=JO&ceid=JO:en",
     "rss", "rss", None, "newspaper", "en", 15, 7.0, "medium"),
    ("Khmer Times (via GN)", "高棉时报", "KH", "https://www.khmertimeskh.com",
     "https://news.google.com/rss/search?q=site:khmertimeskh.com&hl=en&gl=KH&ceid=KH:en",
     "rss", "rss", None, "newspaper", "en", 15, 7.0, "medium"),
    ("Kuwait Times (via GN)", "科威特时报", "KW", "https://www.kuwaittimes.com",
     "https://news.google.com/rss/search?q=site:kuwaittimes.com&hl=en&gl=KW&ceid=KW:en",
     "rss", "rss", None, "newspaper", "en", 15, 8.0, "medium"),
    ("L'Orient-Le Jour (via GN)", "东方日报(黎巴嫩)", "LB", "https://www.lorientlejour.com",
     "https://news.google.com/rss/search?q=site:lorientlejour.com&hl=fr&gl=LB&ceid=LB:fr",
     "rss", "rss", None, "newspaper", "fr", 15, 7.0, "medium"),
    ("Daily News (LK via GN)", "每日新闻(斯里兰卡)", "LK", "https://www.dailynews.lk",
     "https://news.google.com/rss/search?q=site:dailynews.lk&hl=en&gl=LK&ceid=LK:en",
     "rss", "rss", None, "newspaper", "en", 15, 7.0, "medium"),
    ("The Irrawaddy (via GN)", "伊洛瓦底(缅甸)", "MM", "https://www.irrawaddy.com",
     "https://news.google.com/rss/search?q=site:irrawaddy.com&hl=en&gl=MM&ceid=MM:en",
     "rss", "rss", None, "online", "en", 15, 8.0, "medium"),
    ("The Star (via GN)", "星报(马来西亚)", "MY", "https://www.thestar.com.my",
     "https://news.google.com/rss/search?q=site:thestar.com.my&hl=en&gl=MY&ceid=MY:en",
     "rss", "rss", None, "newspaper", "en", 15, 10.0, "medium"),
    ("Kathmandu Post (via GN)", "加德满都邮报", "NP", "https://kathmandupost.com",
     "https://news.google.com/rss/search?q=site:kathmandupost.com&hl=en&gl=NP&ceid=NP:en",
     "rss", "rss", None, "newspaper", "en", 15, 7.0, "medium"),
    ("El Comercio (via GN)", "商报(秘鲁)", "PE", "https://elcomercio.pe",
     "https://news.google.com/rss/search?q=site:elcomercio.pe&hl=es&gl=PE&ceid=PE:es",
     "rss", "rss", None, "newspaper", "es", 15, 11.0, "medium"),
    ("Inquirer (via GN)", "菲律宾每日问询者报", "PH", "https://newsinfo.inquirer.net",
     "https://news.google.com/rss/search?q=site:inquirer.net&hl=en&gl=PH&ceid=PH:en",
     "rss", "rss", None, "newspaper", "en", 15, 10.0, "medium"),
    ("Straits Times (via GN)", "海峡时报(新加坡)", "SG", "https://www.straitstimes.com",
     "https://news.google.com/rss/search?q=site:straitstimes.com&hl=en&gl=SG&ceid=SG:en",
     "rss", "rss", None, "newspaper", "en", 15, 11.0, "medium"),
    # ---- 重点国家大幅扩充(2026-08-04):US 从 2 源扩到 10+,G20 各国 3-8 源,覆盖主流/立场光谱 ----
    # 美国主流媒体扩充(原仅 VOA + Investing.com,覆盖严重不足)
    ("CNN", "美国有线电视新闻网", "US", "https://www.cnn.com",
     "http://rss.cnn.com/rss/cnn_topstories.rss", "rss", "rss", None,
     "broadcast", "en", 10, 18.0, "high"),
    ("Fox News", "福克斯新闻", "US", "https://www.foxnews.com",
     "https://moxie.foxnews.com/google-publisher/latest.xml", "rss", "rss", None,
     "broadcast", "en", 10, 17.0, "high"),
    ("NBC News", "全国广播公司", "US", "https://www.nbcnews.com",
     "https://feeds.nbcnews.com/nbcnews/public/news", "rss", "rss", None,
     "broadcast", "en", 15, 15.0, "high"),
    ("ABC News (US)", "美国广播公司", "US", "https://abcnews.go.com",
     "https://abcnews.go.com/abcnews/topstories", "rss", "rss", None,
     "broadcast", "en", 15, 14.0, "high"),
    ("CBS News", "哥伦比亚广播公司", "US", "https://www.cbsnews.com",
     "https://www.cbsnews.com/latest/rss/main", "rss", "rss", None,
     "broadcast", "en", 15, 14.0, "high"),
    ("NPR", "美国国家公共广播电台", "US", "https://www.npr.org",
     "https://feeds.npr.org/1001/rss.xml", "rss", "rss", None,
     "broadcast", "en", 15, 13.0, "high"),
    ("The New York Times (via GN)", "纽约时报", "US", "https://www.nytimes.com",
     "https://news.google.com/rss/search?q=site:nytimes.com&hl=en&gl=US&ceid=US:en",
     "rss", "rss", None, "newspaper", "en", 15, 17.0, "high"),
    ("Washington Post (via GN)", "华盛顿邮报", "US", "https://www.washingtonpost.com",
     "https://news.google.com/rss/search?q=site:washingtonpost.com&hl=en&gl=US&ceid=US:en",
     "rss", "rss", None, "newspaper", "en", 15, 16.0, "high"),
    ("Wall Street Journal (via GN)", "华尔街日报", "US", "https://www.wsj.com",
     "https://news.google.com/rss/search?q=site:wsj.com&hl=en&gl=US&ceid=US:en",
     "rss", "rss", None, "newspaper", "en", 15, 15.0, "high"),
    ("Politico", "政客", "US", "https://www.politico.com",
     "https://www.politico.com/rss/politicopicks.xml", "rss", "rss", None,
     "online", "en", 15, 11.0, "high"),
    ("The Hill", "国会山报", "US", "https://thehill.com",
     "https://thehill.com/feed/", "rss", "rss", None,
     "online", "en", 15, 10.0, "high"),
    ("AP News", "美联社", "US", "https://apnews.com",
     "https://news.google.com/rss/search?q=site:apnews.com&hl=en&gl=US&ceid=US:en",
     "rss", "rss", None, "agency", "en", 10, 18.0, "high"),
    ("Bloomberg (via GN)", "彭博社", "US", "https://www.bloomberg.com",
     "https://news.google.com/rss/search?q=site:bloomberg.com&hl=en&gl=US&ceid=US:en",
     "rss", "rss", None, "agency", "en", 15, 14.0, "high"),
    ("USA Today (via GN)", "今日美国", "US", "https://www.usatoday.com",
     "https://news.google.com/rss/search?q=site:usatoday.com&hl=en&gl=US&ceid=US:en",
     "rss", "rss", None, "newspaper", "en", 15, 12.0, "medium"),
    # 英国补 3 源
    ("Sky News", "天空新闻", "GB", "https://news.sky.com",
     "https://feeds.skynews.com/feeds/rss/home.xml", "rss", "rss", None,
     "broadcast", "en", 15, 13.0, "high"),
    ("The Telegraph (via GN)", "每日电讯报", "GB", "https://www.telegraph.co.uk",
     "https://news.google.com/rss/search?q=site:telegraph.co.uk&hl=en&gl=GB&ceid=GB:en",
     "rss", "rss", None, "newspaper", "en", 15, 12.0, "high"),
    ("The Times (via GN)", "泰晤士报", "GB", "https://www.thetimes.co.uk",
     "https://news.google.com/rss/search?q=site:thetimes.co.uk&hl=en&gl=GB&ceid=GB:en",
     "rss", "rss", None, "newspaper", "en", 15, 12.0, "high"),
    ("Reuters (via GN)", "路透社", "GB", "https://www.reuters.com",
     "https://news.google.com/rss/search?q=site:reuters.com&hl=en&gl=GB&ceid=GB:en",
     "rss", "rss", None, "agency", "en", 10, 18.0, "high"),
    ("Financial Times (via GN)", "金融时报", "GB", "https://www.ft.com",
     "https://news.google.com/rss/search?q=site:ft.com&hl=en&gl=GB&ceid=GB:en",
     "rss", "rss", None, "newspaper", "en", 15, 13.0, "high"),
    # 法国/德国/意大利/西班牙
    ("Le Monde (via GN)", "世界报(法国)", "FR", "https://www.lemonde.fr",
     "https://news.google.com/rss/search?q=site:lemonde.fr&hl=fr&gl=FR&ceid=FR:fr",
     "rss", "rss", None, "newspaper", "fr", 15, 14.0, "high"),
    ("Le Figaro (via GN)", "费加罗报", "FR", "https://www.lefigaro.fr",
     "https://news.google.com/rss/search?q=site:lefigaro.fr&hl=fr&gl=FR&ceid=FR:fr",
     "rss", "rss", None, "newspaper", "fr", 15, 12.0, "high"),
    ("AFP (via GN)", "法新社", "FR", "https://www.afp.com",
     "https://news.google.com/rss/search?q=site:afp.com&hl=fr&gl=FR&ceid=FR:fr",
     "rss", "rss", None, "agency", "fr", 10, 16.0, "high"),
    ("Der Spiegel (via GN)", "明镜周刊", "DE", "https://www.spiegel.de",
     "https://news.google.com/rss/search?q=site:spiegel.de&hl=de&gl=DE&ceid=DE:de",
     "rss", "rss", None, "newspaper", "de", 15, 14.0, "high"),
    ("Frankfurter Allgemeine (via GN)", "法兰克福汇报", "DE", "https://www.faz.net",
     "https://news.google.com/rss/search?q=site:faz.net&hl=de&gl=DE&ceid=DE:de",
     "rss", "rss", None, "newspaper", "de", 15, 12.0, "high"),
    ("Süddeutsche Zeitung (via GN)", "南德意志报", "DE", "https://www.sueddeutsche.de",
     "https://news.google.com/rss/search?q=site:sueddeutsche.de&hl=de&gl=DE&ceid=DE:de",
     "rss", "rss", None, "newspaper", "de", 15, 12.0, "high"),
    ("La Repubblica (via GN)", "共和国报(意大利)", "IT", "https://www.repubblica.it",
     "https://news.google.com/rss/search?q=site:repubblica.it&hl=it&gl=IT&ceid=IT:it",
     "rss", "rss", None, "newspaper", "it", 15, 12.0, "high"),
    ("El Mundo (via GN)", "世界报(西班牙)", "ES", "https://www.elmundo.es",
     "https://news.google.com/rss/search?q=site:elmundo.es&hl=es&gl=ES&ceid=ES:es",
     "rss", "rss", None, "newspaper", "es", 15, 12.0, "high"),
    # 俄罗斯/日本/韩国
    ("RT", "今日俄罗斯", "RU", "https://www.rt.com",
     "https://www.rt.com/rss/news/", "rss", "rss", None,
     "broadcast", "en", 15, 12.0, "high"),
    ("Interfax", "国际文传电讯社", "RU", "https://www.interfax.ru",
     "https://www.interfax.ru/rss.asp", "rss", "rss", None,
     "agency", "ru", 15, 13.0, "high"),
    ("Asahi Shimbun (via GN)", "朝日新闻", "JP", "https://www.asahi.com",
     "https://news.google.com/rss/search?q=site:asahi.com&hl=ja&gl=JP&ceid=JP:ja",
     "rss", "rss", None, "newspaper", "ja", 15, 14.0, "high"),
    ("Yomiuri Shimbun (via GN)", "读卖新闻", "JP", "https://www.yomiuri.co.jp",
     "https://news.google.com/rss/search?q=site:yomiuri.co.jp&hl=ja&gl=JP&ceid=JP:ja",
     "rss", "rss", None, "newspaper", "ja", 15, 14.0, "high"),
    ("Nikkei (via GN)", "日本经济新闻", "JP", "https://www.nikkei.com",
     "https://news.google.com/rss/search?q=site:nikkei.com&hl=ja&gl=JP&ceid=JP:ja",
     "rss", "rss", None, "newspaper", "ja", 15, 13.0, "high"),
    ("Chosun Ilbo (via GN)", "朝鲜日报", "KR", "https://www.chosun.com",
     "https://news.google.com/rss/search?q=site:chosun.com&hl=ko&gl=KR&ceid=KR:ko",
     "rss", "rss", None, "newspaper", "ko", 15, 13.0, "high"),
    ("JoongAng Ilbo (via GN)", "中央日报(韩国)", "KR", "https://joongang.joins.com",
     "https://news.google.com/rss/search?q=site:joongang.joins.com&hl=ko&gl=KR&ceid=KR:ko",
     "rss", "rss", None, "newspaper", "ko", 15, 12.0, "high"),
    # 中国扩充
    ("人民日报", "人民日报", "CN", "http://www.people.com.cn",
     "http://www.people.com.cn/rss/politics.xml", "rss", "rss", None,
     "newspaper", "zh-CN", 10, 18.0, "high"),
    ("环球时报", "环球时报", "CN", "https://www.globaltimes.cn",
     "https://www.globaltimes.cn/rss/outbrain.xml", "rss", "rss", None,
     "newspaper", "en", 15, 13.0, "high"),
    ("CGTN", "中国国际电视台", "CN", "https://www.cgtn.com",
     "https://www.cgtn.com/subscribe/rss/section/world.xml", "rss", "rss", None,
     "broadcast", "en", 15, 13.0, "high"),
    ("财新网 (via GN)", "财新网", "CN", "https://www.caixin.com",
     "https://news.google.com/rss/search?q=site:caixin.com&hl=zh-CN&gl=CN&ceid=CN:zh-CN",
     "rss", "rss", None, "newspaper", "zh-CN", 15, 12.0, "medium"),
    ("澎湃新闻 (via GN)", "澎湃新闻", "CN", "https://www.thepaper.cn",
     "https://news.google.com/rss/search?q=site:thepaper.cn&hl=zh-CN&gl=CN&ceid=CN:zh-CN",
     "rss", "rss", None, "online", "zh-CN", 15, 11.0, "medium"),
    # 印度/巴基斯坦/孟加拉
    ("Hindustan Times (via GN)", "印度斯坦时报", "IN", "https://www.hindustantimes.com",
     "https://news.google.com/rss/search?q=site:hindustantimes.com&hl=en&gl=IN&ceid=IN:en",
     "rss", "rss", None, "newspaper", "en", 15, 13.0, "high"),
    ("Indian Express (via GN)", "印度快报", "IN", "https://indianexpress.com",
     "https://news.google.com/rss/search?q=site:indianexpress.com&hl=en&gl=IN&ceid=IN:en",
     "rss", "rss", None, "newspaper", "en", 15, 12.0, "high"),
    ("NDTV", "新德里电视台", "IN", "https://www.ndtv.com",
     "https://feeds.feedburner.com/ndtvnews-top-stories", "rss", "rss", None,
     "broadcast", "en", 15, 12.0, "high"),
    ("Geo News", "Geo新闻(巴基斯坦)", "PK", "https://www.geo.tv",
     "https://www.geo.tv/rss/1/1", "rss", "rss", None,
     "broadcast", "en", 15, 10.0, "high"),
    ("Prothom Alo (via GN)", "曙光日报(孟加拉)", "BD", "https://www.prothomalo.com",
     "https://news.google.com/rss/search?q=site:prothomalo.com&hl=bn&gl=BD&ceid=BD:bn",
     "rss", "rss", None, "newspaper", "bn", 15, 10.0, "high"),
    # 中东/以色列/土耳其
    ("Jerusalem Post (via GN)", "耶路撒冷邮报", "IL", "https://www.jpost.com",
     "https://news.google.com/rss/search?q=site:jpost.com&hl=en&gl=IL&ceid=IL:en",
     "rss", "rss", None, "newspaper", "en", 15, 11.0, "high"),
    ("Arab News", "阿拉伯新闻", "SA", "https://www.arabnews.com",
     "https://www.arabnews.com/rss.xml", "rss", "rss", None,
     "newspaper", "en", 15, 11.0, "high"),
    ("Daily Sabah", "每日晨报(土耳其)", "TR", "https://www.dailysabah.com",
     "https://www.dailysabah.com/rss", "rss", "rss", None,
     "newspaper", "en", 15, 10.0, "high"),
    # 拉美
    ("O Globo", "环球报(巴西)", "BR", "https://oglobo.globo.com",
     "https://oglobo.globo.com/rss.xml", "rss", "rss", None,
     "newspaper", "pt", 15, 13.0, "high"),
    ("Estadão", "圣保罗州报", "BR", "https://www.estadao.com.br",
     "https://www.estadao.com.br/rss/ultimas.xml", "rss", "rss", None,
     "newspaper", "pt", 15, 12.0, "high"),
    ("Milenio (via GN)", "千年报(墨西哥)", "MX", "https://www.milenio.com",
     "https://news.google.com/rss/search?q=site:milenio.com&hl=es&gl=MX&ceid=MX:es",
     "rss", "rss", None, "newspaper", "es", 15, 11.0, "high"),
    ("Reforma (via GN)", "改革报(墨西哥)", "MX", "https://www.reforma.com",
     "https://news.google.com/rss/search?q=site:reforma.com&hl=es&gl=MX&ceid=MX:es",
     "rss", "rss", None, "newspaper", "es", 15, 11.0, "high"),
    ("La Nación (AR)", "国家报(阿根廷)", "AR", "https://www.lanacion.com.ar",
     "https://www.lanacion.com.ar/arc/outboundfeeds/rss/?outputType=xml", "rss", "rss", None,
     "newspaper", "es", 15, 12.0, "high"),
    ("El Mercurio (via GN)", "信使报(智利)", "CL", "https://www.emol.com",
     "https://news.google.com/rss/search?q=site:emol.com&hl=es&gl=CL&ceid=CL:es",
     "rss", "rss", None, "newspaper", "es", 15, 11.0, "high"),
    # 非洲补强
    ("Nation Africa", "国家报(肯尼亚/东非)", "KE", "https://nation.africa",
     "https://nation.africa/kenya/rss", "rss", "rss", None,
     "newspaper", "en", 15, 11.0, "high"),
    ("Premium Times", "时代报(尼日利亚)", "NG", "https://www.premiumtimesng.com",
     "https://www.premiumtimesng.com/feed", "rss", "rss", None,
     "online", "en", 15, 10.0, "high"),
    ("News24", "新闻24(南非)", "ZA", "https://www.news24.com",
     "https://www.news24.com/news24/southafrica/rss", "rss", "rss", None,
     "online", "en", 15, 11.0, "high"),
    ("Egypt Independent", "埃及独立报", "EG", "https://www.egyptindependent.com",
     "https://www.egyptindependent.com/feed/", "rss", "rss", None,
     "newspaper", "en", 15, 9.0, "high"),
    # 东南亚/大洋洲补强
    ("Jakarta Post (via GN)", "雅加达邮报", "ID", "https://www.thejakartapost.com",
     "https://news.google.com/rss/search?q=site:thejakartapost.com&hl=en&gl=ID&ceid=ID:en",
     "rss", "rss", None, "newspaper", "en", 15, 11.0, "high"),
    ("Kompas (via GN)", "罗盘报(印尼)", "ID", "https://www.kompas.com",
     "https://news.google.com/rss/search?q=site:kompas.com&hl=id&gl=ID&ceid=ID:id",
     "rss", "rss", None, "newspaper", "id", 15, 12.0, "high"),
    ("Manila Bulletin (via GN)", "马尼拉公报", "PH", "https://mb.com.ph",
     "https://news.google.com/rss/search?q=site:mb.com.ph&hl=en&gl=PH&ceid=PH:en",
     "rss", "rss", None, "newspaper", "en", 15, 10.0, "high"),
    ("Sydney Morning Herald (via GN)", "悉尼先驱晨报", "AU", "https://www.smh.com.au",
     "https://news.google.com/rss/search?q=site:smh.com.au&hl=en&gl=AU&ceid=AU:en",
     "rss", "rss", None, "newspaper", "en", 15, 12.0, "high"),
    ("The Australian (via GN)", "澳大利亚人报", "AU", "https://www.theaustralian.com.au",
     "https://news.google.com/rss/search?q=site:theaustralian.com.au&hl=en&gl=AU&ceid=AU:en",
     "rss", "rss", None, "newspaper", "en", 15, 11.0, "high"),
    # 加拿大补强
    ("Globe and Mail (via GN)", "环球邮报(加拿大)", "CA", "https://www.theglobeandmail.com",
     "https://news.google.com/rss/search?q=site:theglobeandmail.com&hl=en&gl=CA&ceid=CA:en",
     "rss", "rss", None, "newspaper", "en", 15, 12.0, "high"),
    ("Toronto Star (via GN)", "多伦多星报", "CA", "https://www.thestar.com",
     "https://news.google.com/rss/search?q=site:thestar.com&hl=en&gl=CA&ceid=CA:en",
     "rss", "rss", None, "newspaper", "en", 15, 10.0, "high"),
    # ---- 重点国每国 ≥2 源补足(2026-08-04):G20 与地缘政治热点国加第二/三源,提升覆盖冗余 ----
    # 中东热点
    ("Al Arabiya", "阿拉比亚电视台", "SA", "https://www.alarabiya.net",
     "https://www.alarabiya.net/.mrss/en/rss.xml", "rss", "rss", None,
     "broadcast", "en", 15, 11.0, "high"),
    ("Middle East Eye", "中东之眼", "QA", "https://www.middleeasteye.net",
     "https://www.middleeasteye.net/rss", "rss", "rss", None,
     "online", "en", 15, 10.0, "high"),
    ("Israel Hayom (via GN)", "今日以色列", "IL", "https://www.israelhayom.com",
     "https://news.google.com/rss/search?q=site:israelhayom.com&hl=en&gl=IL&ceid=IL:en",
     "rss", "rss", None, "newspaper", "en", 15, 10.0, "high"),
    ("Al-Monitor", "中东观察", "US", "https://www.al-monitor.com",
     "https://www.al-monitor.com/rss", "rss", "rss", None,
     "online", "en", 15, 9.0, "high"),
    # 东南亚
    ("Channel News Asia", "亚洲新闻台", "SG", "https://www.channelnewsasia.com",
     "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511",
     "rss", "rss", None, "broadcast", "en", 15, 12.0, "high"),
    ("VietnamPlus", "越南加", "VN", "https://en.vietnamplus.vn",
     "https://en.vietnamplus.vn/rss", "rss", "rss", None,
     "agency", "en", 15, 10.0, "high"),
    ("Thai PBS", "泰国公共广播", "TH", "https://www.thaipbs.or.th",
     "https://www.thaipbs.or.th/rss/news", "rss", "rss", None,
     "broadcast", "th", 15, 9.0, "high"),
    # 南亚
    ("Himalayan Times", "喜马拉雅时报(尼泊尔)", "NP", "https://thehimalayantimes.com",
     "https://thehimalayantimes.com/rssFeed/0", "rss", "rss", None,
     "newspaper", "en", 15, 8.0, "high"),
    ("Ceylon Today", "今日锡兰(斯里兰卡)", "LK", "https://ceylontoday.lk",
     "https://ceylontoday.lk/rss.xml", "rss", "rss", None,
     "newspaper", "en", 15, 7.0, "high"),
    # 欧洲 G20 补足
    ("De Volkskrant (via GN)", "人民报(荷兰)", "NL", "https://www.volkskrant.nl",
     "https://news.google.com/rss/search?q=site:volkskrant.nl&hl=nl&gl=NL&ceid=NL:nl",
     "rss", "rss", None, "newspaper", "nl", 15, 10.0, "high"),
    ("Aftonbladet", "晚报(瑞典)", "SE", "https://www.aftonbladet.se",
     "https://rss.aftonbladet.se/rss2/small/pages/sections/senastenytt/", "rss", "rss", None,
     "newspaper", "sv", 15, 10.0, "high"),
    ("NRK P2", "挪威广播二台", "NO", "https://www.nrk.no",
     "https://www.nrk.no/norge/toppsaker.rss", "rss", "rss", None,
     "broadcast", "no", 15, 10.0, "high"),
    ("YLE", "芬兰国家广播", "FI", "https://yle.fi",
     "https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_UUTISET", "rss", "rss", None,
     "broadcast", "fi", 15, 10.0, "high"),
    ("Politiken", "政治报(丹麦)", "DK", "https://politiken.dk",
     "https://politiken.dk/rss/senestenyt.rss", "rss", "rss", None,
     "newspaper", "da", 15, 9.0, "high"),
    ("RTE", "爱尔兰广播电视", "IE", "https://www.rte.ie",
     "https://www.rte.ie/news/rss/news-headlines.xml", "rss", "rss", None,
     "broadcast", "en", 15, 10.0, "high"),
    # 拉美
    ("El Universal (MX)", "环球报(墨西哥)", "MX", "https://www.eluniversal.com.mx",
     "https://www.eluniversal.com.mx/rss.xml", "rss", "rss", None,
     "newspaper", "es", 15, 10.0, "high"),
    ("Infobae", "Infobae(阿根廷)", "AR", "https://www.infobae.com",
     "https://www.infobae.com/feeds/rss/", "rss", "rss", None,
     "online", "es", 15, 12.0, "high"),
    ("El Comercio (PE)", "商报(秘鲁)", "PE", "https://elcomercio.pe",
     "https://elcomercio.pe/arc/outboundfeeds/rss/?outputType=xml", "rss", "rss", None,
     "newspaper", "es", 15, 10.0, "high"),
    ("Semana", "周刊(哥伦比亚)", "CO", "https://www.semana.com",
     "https://www.semana.com/rss/", "rss", "rss", None,
     "newspaper", "es", 15, 10.0, "high"),
    ("El País (UY)", "国家报(乌拉圭)", "UY", "https://www.elpais.com.uy",
     "https://www.elpais.com.uy/rss/", "rss", "rss", None,
     "newspaper", "es", 15, 9.0, "high"),
    # 非洲补足
    ("Jeune Afrique", "青年非洲", "CI", "https://www.jeuneafrique.com",
     "https://www.jeuneafrique.com/feed/", "rss", "rss", None,
     "newspaper", "fr", 15, 10.0, "high"),
    ("Al-Ahram (via GN)", "金字塔报(埃及)", "EG", "https://english.ahram.org.eg",
     "https://news.google.com/rss/search?q=site:english.ahram.org.eg&hl=en&gl=EG&ceid=EG:en",
     "rss", "rss", None, "newspaper", "en", 15, 10.0, "high"),
    ("Daily Maverick", "每日独立评论(南非)", "ZA", "https://www.dailymaverick.co.za",
     "https://www.dailymaverick.co.za/feed/", "rss", "rss", None,
     "online", "en", 15, 10.0, "high"),
    ("The East African", "东非报(肯尼亚)", "KE", "https://www.theeastafrican.co.ke",
     "https://www.theeastafrican.co.ke/rss", "rss", "rss", None,
     "newspaper", "en", 15, 9.0, "high"),
    ("New Vision", "新视野(乌干达)", "UG", "https://www.newvision.co.ug",
     "https://www.newvision.co.ug/rss/", "rss", "rss", None,
     "newspaper", "en", 15, 9.0, "high"),
    ("Daily News Egypt (backup)", "埃及每日新闻(备用)", "EG", "https://www.dailynewsegypt.com",
     "https://www.dailynewsegypt.com/feed/", "rss", "rss", None,
     "newspaper", "en", 15, 8.0, "high"),
    # 中亚/高加索
    ("Kazinform", "哈萨克国际通讯社", "KZ", "https://qazinform.com",
     "https://qazinform.com/rss", "rss", "rss", None,
     "agency", "en", 15, 9.0, "high"),
    ("Ukrinform", "乌克兰国家通讯社", "UA", "https://www.ukrinform.net",
     "https://www.ukrinform.net/rss/block-lastnews", "rss", "rss", None,
     "agency", "en", 15, 11.0, "high"),
    ("Kyiv Independent", "基辅独立报", "UA", "https://kyivindependent.com",
     "https://kyivindependent.com/feed/", "rss", "rss", None,
     "online", "en", 15, 10.0, "high"),
    # 其他 G20
    ("Bild (via GN)", "图片报(德国)", "DE", "https://www.bild.de",
     "https://news.google.com/rss/search?q=site:bild.de&hl=de&gl=DE&ceid=DE:de",
     "rss", "rss", None, "newspaper", "de", 15, 11.0, "high"),
    ("Il Sole 24 Ore", "24小时太阳报(意大利)", "IT", "https://www.ilsole24ore.com",
     "https://www.ilsole24ore.com/rss/italia.xml", "rss", "rss", None,
     "newspaper", "it", 15, 10.0, "high"),
    ("Correio Braziliense", "巴西利亚邮报", "BR", "https://www.correiobraziliense.com.br",
     "https://www.correiobraziliense.com.br/rss.xml", "rss", "rss", None,
     "newspaper", "pt", 15, 10.0, "high"),
]


def main() -> None:
    configure_logging(debug=False)
    init_engine()
    db = get_session_factory()()
    try:
        admin = ensure_admin(db)
        ensure_system_rules(db, admin)
        ensure_gdelt_pseudo_source(db)

        created = updated = 0
        for (name, name_zh, country, homepage, feed_url, collect_mode, adapter_type,
             crawl_config, media_type, language, poll_interval, weight, confidence) in SEED_SOURCES:
            source = db.scalar(select(Source).where(Source.name == name))
            fields = {
                "name_zh": name_zh, "country_code": country, "homepage_url": homepage,
                "feed_url": feed_url, "collect_mode": collect_mode, "adapter_type": adapter_type,
                "crawl_config": crawl_config or {}, "media_type": media_type, "language": language,
                "poll_interval_min": poll_interval, "audience_weight": weight,
                "coverage_confidence": confidence,
            }
            if source is None:
                db.add(Source(name=name, **fields))
                created += 1
            else:
                for key, value in fields.items():
                    setattr(source, key, value)
                updated += 1
        db.commit()
        # 监控范围生效（T5.6）：安装向导已保存勾选国家时，导入完成后再次应用，
        # 使未勾选国家的源置 disabled（重新导入/补种不丢失范围设定）
        scope = get_state(db, KEY_MONITOR_SCOPE) or {}
        if scope.get("countries"):
            scope_result = apply_monitor_scope(db, scope["countries"])
            db.commit()
            logger.info("monitor_scope_applied", **scope_result)
        logger.info("seed_done", created=created, updated=updated,
                    admin=admin.username, total=len(SEED_SOURCES))
        print(f"种子导入完成: 新增 {created} / 更新 {updated} / 共 {len(SEED_SOURCES)} 个媒体源；管理员 {admin.username}")
    finally:
        db.close()


if __name__ == "__main__":
    main()
